---
development:
  cloud_name: doohavoda
  api_key: '231138229721459'
  api_secret: q60DjdCIUGQGItOaQlwE0tZYZk0
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: doohavoda
  api_key: '231138229721459'
  api_secret: q60DjdCIUGQGItOaQlwE0tZYZk0
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: doohavoda
  api_key: '231138229721459'
  api_secret: q60DjdCIUGQGItOaQlwE0tZYZk0
  enhance_image_tag: true
  static_image_support: false